plugins {
    id('com.android.application')
    id('org.jetbrains.kotlin.android')
    id("de.undercouch.download") version "5.6.0"
}

android {
    compileSdk 35
    defaultConfig {
        applicationId "de.jade_hs.afex"
        minSdkVersion 26
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    namespace 'de.jade_hs.afex'
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

// import DownloadModels task
project.ext.ASSET_DIR = projectDir.toString() + '/src/main/assets'
project.ext.TEST_ASSET_DIR = projectDir.toString() + '/src/androidTest/assets'
apply from:'download_model.gradle'

dependencies {

    // tinylog logging framework
    implementation 'org.tinylog:tinylog:1.3.5'

    // JTransforms FFT library
    implementation 'com.github.wendykierp:JTransforms:3.1'

    // ThreeTen Android Backport date and time library (TODO: deprecated)
    implementation 'com.jakewharton.threetenabp:threetenabp:1.2.1'

    // mediapipe Library
    //implementation 'com.google.mediapipe:tasks-audio:0.20230731'
    implementation 'com.google.mediapipe:tasks-audio:0.10.26.1'

    // WebRTC VAD - https://github.com/gkonovalov/android-vad
    //implementation 'com.github.gkonovalov.android-vad:webrtc:2.0.9'

    // Silero VAD - https://github.com/gkonovalov/android-vad
    implementation 'com.github.gkonovalov.android-vad:silero:2.0.9'

    // Yamnet VAD - https://github.com/gkonovalov/android-vad
    //implementation 'com.github.gkonovalov.android-vad:yamnet:2.0.9'

    // ONNX Runtime
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:latest.release'

    // Kotlin lang
    implementation 'androidx.core:core-ktx:1.15.0'

    // App compat and UI
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.fragment:fragment-ktx:1.8.6'

    // Navigation library
    def nav_version = "2.8.9"
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

    // Unit testing
    testImplementation 'junit:junit:4.13.2'

    // Instrumented testing
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}
